### PR TITLE
Fix/unit testing

### LINKED ISSUE #19: ## Testing
- [x] Refactor existing tests.
- [x] Add tests for sad paths.
- [x] Ensure all class's and class methods are tested.

### PR DESCRIPTION
**Pull request by LukeMason33**
## Pull Request

<br>

### Description

* Is this a feature or a fix?
This is a fix. It contains the complete redo of our unit tests for our two classes, User and Recipe. All methods and properties are tested using sample data sets that are located in the data directory. These data miles mock the data that is returned from our network requests in the fetch.js file.

* Where should the reviewer start?
The reviewer should start in the test directory.

* What functionalities do these changes effect? What was the motivation behind these changes?
This does not change any of the functionality within our site. But there was a last minute commit on getting the cost of a recipe to display in the recipe cards.

* What outside features or research did you use to implement this fix?
I was using Postman to see how the data was being returned and wrote the tests according to that.

* How should this be tested?
This should be tested by running "npm start" in your terminal to ensure all the unit testing is passing.

* Applicable screenshot(s): 

<br>

***

#### Please review considerations below:

- [ ] Follows Turing Style Guidelines
- [ ] Changes generate no new warnings or errors(linter etc)
- [ ] README has been updated(if applicable)

### CODE REVIEW

File: test/user-test.js [hunk 1]
```diff
@@ -31,30 +32,47 @@ describe('User', function() {
...
   });
 
   it('should be able to decide to cook a recipe', function() {
-    user.decideToCook(recipe);
-    expect(user.recipesToCook[0].name).to.equal('Chicken Parm');
+    user.saveRecipe(recipe, 'recipesToCook');
+    expect(user.recipesToCook[0]).to.deep.eq(recipe);
+  });
+
+  it('should be able remove recipes from favoriteRecipes after they are addede in', function() {
```
Comment (kristenmb) [inline test/user-test.js:52]: Small typo here!

File: test/user-test.js [hunk 2]
```diff
@@ -31,30 +32,47 @@ describe('User', function() {
...
+    user.saveRecipe(recipe, 'favoriteRecipes');
+    user.removeRecipe(recipe, 'favoriteRecipes');
+    expect(user.favoriteRecipes).to.deep.eq([]);
+  });
+
+  it('should be able remove recipes from recipesToCook after they are addede in', function() {
```
Comment (kristenmb) [inline test/user-test.js:58]: small typo!

**Comment by kristenmb** [comment]
Thanks for taking care of the cost display on the card - super helpful! These tests look great - I found two small typos in the user-tests but they will be quick fixes.
